# name: Comments
# on:
#   repository_dispatch:
#     types: [trigger-workflow-2]
#   pull_request_target:
#     types:
#       - opened
# jobs:
#   example_comment_pr:
#     runs-on: ubuntu-latest
#     name: An example job to comment a PR
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v1
#         with:
#           message: |
#             atlantis plan
#       - name: Trigger next workflow
#         if: success()
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           event-type: trigger-workflow-3
#   triage:
#     permissions:
#       contents: read
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/labeler@v4
#       with:
#         repo-token: "${{ secrets.GITHUB_TOKEN }}"        