# name: Comments
# on:
#   pull_request:
#     types: [opened]
#     branches: atlantis

# jobs:
#   example_comment_pr:
#     runs-on: ubuntu-latest
#     name: An example job to comment a PR Whoop
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v1
#         with:
#           message: |
#             atlantis plan

