name: Comments
on:
  pull_request:
  repository_dispatch:
    types: [trigger-workflow-2]
  pull_request_target:
    types:
      - opened
      - labeled
jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            atlantis plan
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ github.repository }}
          event-type: trigger-workflow-3
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'                 