name: Pull Request Action
on:
  push:
  pull_request_target:
    types:
      - opened
      - unlabeled  
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr, automerge"
          pr_title: "[Example] Simple demo"     