name: Auto PR
on:
  push:
    branches: [atlantis]
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Auto PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: atlantis plan
          title: Auto PR
          body: Credit AutoPR
          branch: atlantis
