name: Pull Request Action
on:
  push:
    branches:
      - test

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          pr_label: "feature, automated pr, automerge"
          pr_title: "Auto Created PR with Label"
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'          