name: Pull Request Action
on:
  push:
    branches:
      - atlantis

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr, automerge"
          pr_title: "[Example] Simple demo"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token:  ${{ secrets.REPO_ACCESS_TOken }}
          repository: wbj3rd/hello-world
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'          